In [ ]:
import pandas as pd

In [ ]:
df_reviews = pd.read_json('/content/reviews_data_v3.json', lines=True)
print(df_reviews)

        app_id  parent_app_id  recommendationid   recommendation  \
0      3669570        3669570         223875804      Recommended
1      3669570        3669570         219038522      Recommended
2      3669570        3669570         223815953      Recommended
3      3669570        3669570         223710270  Not Recommended
4      3669570        3669570         223641705      Recommended
...        ...            ...               ...              ...
54406  2957480        1790600         176756097      Recommended
54407  2957480        1790600         176727297  Not Recommended
54408  2957480        1790600         176724096  Not Recommended
54409  2957480        1790600         176716020      Recommended
54410  2957480        1790600         176697534  Not Recommended

                                             review_text review_score  \
0      Really fun actually! Just like a little factor...     positive
1      Just spent 2 hours on making a semi-compact co...     positive
2      I have been taking my time w/this game...makin...     positive
3      Looks like a fun game but holy the belt placem...     negative
4      I like automation games (Factorio, Satisfactor...     positive
...                                                  ...          ...
54406  Peak music, must have for me (but they should ...     positive
54407  I remember playing through the campaign's and ...     negative
54408  beating the ♥♥♥♥ outta people as Goku while CH...     negative
54409  The music is top notch and everything I ever w...     positive
54410  It does not play the music for your opponent w...     negative

       total_playtime_hours  playtime_at_review_hours  votes_up  \
0                      10.7                      10.7         0
1                      70.2                      70.2         0
2                    1376.0                    1364.8         0
3                       2.3                       2.3         2
4                      39.0                       5.0         0
...                     ...                       ...       ...
54406                   0.0                       0.0        37
54407                   0.0                       0.0       163
54408                   0.0                       0.0        70
54409                   0.0                       0.0        26
54410                   0.0                       0.0        54

       steam_purchase  received_for_free  written_during_early_access
0               False              False                         True
1                True              False                         True
2                True              False                         True
3                True              False                         True
4                True              False                         True
...               ...                ...                          ...
54406            True              False                        False
54407            True              False                        False
54408            True              False                        False
54409            True              False                        False
54410            True              False                        False

[54411 rows x 12 columns]

In [ ]:
print(df_reviews.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54411 entries, 0 to 54410
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   app_id                       54411 non-null  int64
 1   parent_app_id                54411 non-null  int64
 2   recommendationid             54411 non-null  int64
 3   recommendation               54411 non-null  object
 4   review_text                  54411 non-null  object
 5   review_score                 54411 non-null  object
 6   total_playtime_hours         54411 non-null  float64
 7   playtime_at_review_hours     54411 non-null  float64
 8   votes_up                     54411 non-null  int64
 9   steam_purchase               54411 non-null  bool
 10  received_for_free            54411 non-null  bool
 11  written_during_early_access  54411 non-null  bool
dtypes: bool(3), float64(2), int64(4), object(3)
memory usage: 3.9+ MB
None

In [ ]:
df_reviews.duplicated(subset=['review_text'])

0        False
1        False
2        False
3        False
4        False
         ...
54405    False
54407    False
54408    False
54409    False
54410    False
Length: 53678, dtype: bool

In [ ]:
df_reviews.drop_duplicates(subset=['review_text'],inplace=True)

In [ ]:
df_reviews.duplicated(subset=['review_text'])

0        False
1        False
2        False
3        False
4        False
         ...
49503    False
49504    False
49505    False
49506    False
49507    False
Length: 48106, dtype: bool

In [ ]:
df_reviews

,app_id,parent_app_id,recommendationid,recommendation,review_text,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,received_for_free,written_during_early_access
0,3669570,3669570,223875804,Recommended,Really fun actually! Just like a little factor...,positive,10.7,10.7,0,False,False,True
1,3669570,3669570,219038522,Recommended,Just spent 2 hours on making a semi-compact co...,positive,70.2,70.2,0,True,False,True
2,3669570,3669570,223815953,Recommended,I have been taking my time w/this game...makin...,positive,1376.0,1364.8,0,True,False,True
3,3669570,3669570,223710270,Not Recommended,Looks like a fun game but holy the belt placem...,negative,2.3,2.3,2,True,False,True
4,3669570,3669570,223641705,Recommended,"I like automation games (Factorio, Satisfactor...",positive,39.0,5.0,0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
54405,2957480,1790600,176774972,Recommended,CHA-LA HEAD CHA-LA\nNani ga okite mo kibun wa ...,positive,0.0,0.0,7,True,False,False
54407,2957480,1790600,176727297,Not Recommended,I remember playing through the campaign's and ...,negative,0.0,0.0,163,True,False,False
54408,2957480,1790600,176724096,Not Recommended,beating the ♥♥♥♥ outta people as Goku while CH...,negative,0.0,0.0,70,True,False,False
54409,2957480,1790600,176716020,Recommended,The music is top notch and everything I ever w...,positive,0.0,0.0,26,True,False,False
54410,2957480,1790600,176697534,Not Recommended,It does not play the music for your opponent w...,negative,0.0,0.0,54,True,False,False

In [ ]:
import re


df_reviews['review_text'] = df_reviews['review_text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))

In [ ]:
df_reviews

,app_id,parent_app_id,recommendation,review_text,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,received_for_free,written_during_early_access
0,2183900,2183900,Recommended,with friends peak \r\nwithout friends peak \r\...,positive,12.1,9.2,29,True,False,False
1,2183900,2183900,Recommended,h2b10 Hours of Pure Testosteronebh2\n\nI went ...,positive,11.9,11.9,163,True,False,False
2,2183900,2183900,Recommended,h3 Warning Can be quite addictive h3\r\nbiFor ...,positive,71.8,71.8,10,True,False,False
3,2183900,2183900,Recommended,Tthe scale of it was impressive It really puts...,positive,14.2,12.8,8,True,False,False
4,2183900,2183900,Recommended,This game is like a Warhammer 40k theme park\n...,positive,231.2,222.3,6,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
49503,3959440,2634950,Recommended,I love the game,positive,0.0,0.0,0,True,False,False
49504,3959440,2634950,Recommended,free car cool girl,positive,0.0,0.0,0,True,False,False
49505,3959440,2634950,Recommended,idk much about anime but i guess we get anothe...,positive,0.0,0.0,0,True,False,False
49506,3959440,2634950,Recommended,RX8,positive,0.0,0.0,1,True,False,False
49507,2419810,1435790,Recommended,my favourite of all the dlcs the magical mecha...,positive,0.0,0.0,0,True,False,False

In [ ]:
df_reviews['review_text'] = df_reviews['review_text'].str.replace(r'\r\n', ' ', regex=True)

In [ ]:
df_reviews

,app_id,parent_app_id,recommendationid,recommendation,review_text,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,received_for_free,written_during_early_access
0,3669570,3669570,223875804,Recommended,Really fun actually Just like a little factori...,positive,10.7,10.7,0,False,False,True
1,3669570,3669570,219038522,Recommended,Just spent 2 hours on making a semicompact cok...,positive,70.2,70.2,0,True,False,True
2,3669570,3669570,223815953,Recommended,I have been taking my time wthis gamemaking bl...,positive,1376.0,1364.8,0,True,False,True
3,3669570,3669570,223710270,Not Recommended,Looks like a fun game but holy the belt placem...,negative,2.3,2.3,2,True,False,True
4,3669570,3669570,223641705,Recommended,I like automation games Factorio Satisfactory ...,positive,39.0,5.0,0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
54405,2957480,1790600,176774972,Recommended,CHALA HEAD CHALA\nNani ga okite mo kibun wa he...,positive,0.0,0.0,7,True,False,False
54407,2957480,1790600,176727297,Not Recommended,I remember playing through the campaigns and w...,negative,0.0,0.0,163,True,False,False
54408,2957480,1790600,176724096,Not Recommended,beating the outta people as Goku while CHA LA...,negative,0.0,0.0,70,True,False,False
54409,2957480,1790600,176716020,Recommended,The music is top notch and everything I ever w...,positive,0.0,0.0,26,True,False,False
54410,2957480,1790600,176697534,Not Recommended,It does not play the music for your opponent w...,negative,0.0,0.0,54,True,False,False

In [ ]:
df_reviews['review_text'] = df_reviews['review_text'].str.replace(r'\n\n', ' ', regex=True)

In [ ]:
df_reviews

,app_id,parent_app_id,recommendationid,recommendation,review_text,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,received_for_free,written_during_early_access
0,3669570,3669570,223875804,Recommended,Really fun actually Just like a little factori...,positive,10.7,10.7,0,False,False,True
1,3669570,3669570,219038522,Recommended,Just spent 2 hours on making a semicompact cok...,positive,70.2,70.2,0,True,False,True
2,3669570,3669570,223815953,Recommended,I have been taking my time wthis gamemaking bl...,positive,1376.0,1364.8,0,True,False,True
3,3669570,3669570,223710270,Not Recommended,Looks like a fun game but holy the belt placem...,negative,2.3,2.3,2,True,False,True
4,3669570,3669570,223641705,Recommended,I like automation games Factorio Satisfactory ...,positive,39.0,5.0,0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
54405,2957480,1790600,176774972,Recommended,CHALA HEAD CHALA\nNani ga okite mo kibun wa he...,positive,0.0,0.0,7,True,False,False
54407,2957480,1790600,176727297,Not Recommended,I remember playing through the campaigns and w...,negative,0.0,0.0,163,True,False,False
54408,2957480,1790600,176724096,Not Recommended,beating the outta people as Goku while CHA LA...,negative,0.0,0.0,70,True,False,False
54409,2957480,1790600,176716020,Recommended,The music is top notch and everything I ever w...,positive,0.0,0.0,26,True,False,False
54410,2957480,1790600,176697534,Not Recommended,It does not play the music for your opponent w...,negative,0.0,0.0,54,True,False,False

In [ ]:
df_reviews.loc[200,'review_text']

'bTLDR  Great Anime Metroidvania of 2026 Dont forget your controller Have funb h1Prosh1 listCharacter designs are great Beautiful soundtracks Combats are very satisfying and addictive bKotama is so cuteb Seriously one of the reasons I bought this game was because of that thumbnail alonelist h1Consh1 listI wished the game were fully voiceacted If that feature ever comes I would definitely go back and play the whole game againlist'

In [ ]:
df_reviews['review_text'] = df_reviews['review_text'].str.replace(r'\n', ' ', regex=True)
df_reviews

,app_id,parent_app_id,recommendationid,recommendation,review_text,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,received_for_free,written_during_early_access
0,3669570,3669570,223875804,Recommended,Really fun actually Just like a little factori...,positive,10.7,10.7,0,False,False,True
1,3669570,3669570,219038522,Recommended,Just spent 2 hours on making a semicompact cok...,positive,70.2,70.2,0,True,False,True
2,3669570,3669570,223815953,Recommended,I have been taking my time wthis gamemaking bl...,positive,1376.0,1364.8,0,True,False,True
3,3669570,3669570,223710270,Not Recommended,Looks like a fun game but holy the belt placem...,negative,2.3,2.3,2,True,False,True
4,3669570,3669570,223641705,Recommended,I like automation games Factorio Satisfactory ...,positive,39.0,5.0,0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
54405,2957480,1790600,176774972,Recommended,CHALA HEAD CHALA Nani ga okite mo kibun wa hen...,positive,0.0,0.0,7,True,False,False
54407,2957480,1790600,176727297,Not Recommended,I remember playing through the campaigns and w...,negative,0.0,0.0,163,True,False,False
54408,2957480,1790600,176724096,Not Recommended,beating the outta people as Goku while CHA LA...,negative,0.0,0.0,70,True,False,False
54409,2957480,1790600,176716020,Recommended,The music is top notch and everything I ever w...,positive,0.0,0.0,26,True,False,False
54410,2957480,1790600,176697534,Not Recommended,It does not play the music for your opponent w...,negative,0.0,0.0,54,True,False,False

In [ ]:
df_reviews.duplicated(subset=['review_text'])

0        False
1        False
2        False
3        False
4        False
         ...
54405    False
54407    False
54408    False
54409    False
54410    False
Length: 53678, dtype: bool

In [ ]:
df_reviews['review_text'] = df_reviews['review_text'].apply(
    lambda x: re.sub(r'\s+', ' ', str(x))
).str.strip()
df_reviews

,app_id,parent_app_id,recommendationid,recommendation,review_text,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,received_for_free,written_during_early_access
0,3669570,3669570,223875804,Recommended,Really fun actually Just like a little factori...,positive,10.7,10.7,0,False,False,True
1,3669570,3669570,219038522,Recommended,Just spent 2 hours on making a semicompact cok...,positive,70.2,70.2,0,True,False,True
2,3669570,3669570,223815953,Recommended,I have been taking my time wthis gamemaking bl...,positive,1376.0,1364.8,0,True,False,True
3,3669570,3669570,223710270,Not Recommended,Looks like a fun game but holy the belt placem...,negative,2.3,2.3,2,True,False,True
4,3669570,3669570,223641705,Recommended,I like automation games Factorio Satisfactory ...,positive,39.0,5.0,0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
54405,2957480,1790600,176774972,Recommended,CHALA HEAD CHALA Nani ga okite mo kibun wa hen...,positive,0.0,0.0,7,True,False,False
54407,2957480,1790600,176727297,Not Recommended,I remember playing through the campaigns and w...,negative,0.0,0.0,163,True,False,False
54408,2957480,1790600,176724096,Not Recommended,beating the outta people as Goku while CHA LA ...,negative,0.0,0.0,70,True,False,False
54409,2957480,1790600,176716020,Recommended,The music is top notch and everything I ever w...,positive,0.0,0.0,26,True,False,False
54410,2957480,1790600,176697534,Not Recommended,It does not play the music for your opponent w...,negative,0.0,0.0,54,True,False,False

In [ ]:
df_reviews['review_text'] = df_reviews['review_text'].apply(
    lambda x: re.sub(r'[^\w\s]', '', str(x))
)
df_reviews

,app_id,parent_app_id,recommendationid,recommendation,review_text,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,received_for_free,written_during_early_access
0,3669570,3669570,223875804,Recommended,Really fun actually Just like a little factori...,positive,10.7,10.7,0,False,False,True
1,3669570,3669570,219038522,Recommended,Just spent 2 hours on making a semicompact cok...,positive,70.2,70.2,0,True,False,True
2,3669570,3669570,223815953,Recommended,I have been taking my time wthis gamemaking bl...,positive,1376.0,1364.8,0,True,False,True
3,3669570,3669570,223710270,Not Recommended,Looks like a fun game but holy the belt placem...,negative,2.3,2.3,2,True,False,True
4,3669570,3669570,223641705,Recommended,I like automation games Factorio Satisfactory ...,positive,39.0,5.0,0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
54405,2957480,1790600,176774972,Recommended,CHALA HEAD CHALA Nani ga okite mo kibun wa hen...,positive,0.0,0.0,7,True,False,False
54407,2957480,1790600,176727297,Not Recommended,I remember playing through the campaigns and w...,negative,0.0,0.0,163,True,False,False
54408,2957480,1790600,176724096,Not Recommended,beating the outta people as Goku while CHA LA ...,negative,0.0,0.0,70,True,False,False
54409,2957480,1790600,176716020,Recommended,The music is top notch and everything I ever w...,positive,0.0,0.0,26,True,False,False
54410,2957480,1790600,176697534,Not Recommended,It does not play the music for your opponent w...,negative,0.0,0.0,54,True,False,False

In [ ]:
df_reviews.duplicated(subset=['review_text'])

0        False
1        False
2        False
3        False
4        False
         ...
54405    False
54407    False
54408    False
54409    False
54410    False
Length: 53489, dtype: bool

In [ ]:
df_reviews.drop_duplicates(subset=['review_text'],inplace=True)

In [ ]:
df_reviews.to_json('reviews_data_cleaned.json', orient='records', lines=True)

print("Data successfully cleaned and saved to 'games_data_cleaned.json'!")

Data successfully cleaned and saved to 'games_data_cleaned.json'!

In [ ]:
df_reviews

,app_id,parent_app_id,recommendation,review_text,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,received_for_free,written_during_early_access
0,2183900,2183900,Recommended,with friends peak without friends peak the gam...,positive,12.1,9.2,29,True,False,False
1,2183900,2183900,Recommended,h2b10 Hours of Pure Testosteronebh2 I went int...,positive,11.9,11.9,163,True,False,False
2,2183900,2183900,Recommended,h3 Warning Can be quite addictive h3 biFor The...,positive,71.8,71.8,10,True,False,False
3,2183900,2183900,Recommended,Tthe scale of it was impressive It really puts...,positive,14.2,12.8,8,True,False,False
4,2183900,2183900,Recommended,This game is like a Warhammer 40k theme park I...,positive,231.2,222.3,6,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
49502,3959440,2634950,Recommended,put Elizabeth Rose Bloodflame in plz,positive,0.0,0.0,0,True,False,False
49504,3959440,2634950,Recommended,free car cool girl,positive,0.0,0.0,0,True,False,False
49505,3959440,2634950,Recommended,idk much about anime but i guess we get anothe...,positive,0.0,0.0,0,True,False,False
49506,3959440,2634950,Recommended,RX8,positive,0.0,0.0,1,True,False,False
49507,2419810,1435790,Recommended,my favourite of all the dlcs the magical mecha...,positive,0.0,0.0,0,True,False,False