# ***Import*** ***libraries***

In [18]:

%pip install plotly

Requirement already satisfied: plotly in c:\users\alkods\appdata\local\programs\python\python313\lib\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\alkods\appdata\local\programs\python\python313\lib\site-packages (from plotly) (2.20.0)
Requirement already satisfied: packaging in c:\users\alkods\appdata\roaming\python\python313\site-packages (from plotly) (25.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
%pip install upgrade pip

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement upgrade (from versions: none)

[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for upgrade

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler,MinMaxScaler,OneHotEncoder
from datetime import datetime
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from collections import Counter
import re

In [21]:
%pip install nbformat

Requirement already satisfied: nbformat in c:\users\alkods\appdata\local\programs\python\python313\lib\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\alkods\appdata\local\programs\python\python313\lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\alkods\appdata\local\programs\python\python313\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\alkods\appdata\roaming\python\python313\site-packages (from nbformat) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\alkods\appdata\roaming\python\python313\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\alkods\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\alkods\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\alkods\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\alkods\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\alkods\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\alkods\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (311)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# ***Reading data***

In [22]:
games_data=pd.read_json('cleaned_games_data (1).json', lines =True)
games_data.head()

,app_id,description,developers,dlc_app_ids,genres,header_image,name,price,publishers,release_date,...,supported_languages,tag,tag_id,total_english_reviews,total_negative,total_positive,total_reviews,url,website,features
0,3669570,‌Alchemy Factory‌ A medieval sandbox blending ...,D5 Copperhead,No DLC,"Casual, Indie, Simulation, Strategy, Early Access",https://shared.akamai.steamstatic.com/store_it...,Alchemy Factory,16.19,Gamirror Games,"Dec 11, 2025",...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,1065,217,1996,2213,https://store.steampowered.com/app/3669570/,None,"Single-player, Multi-player, Co-op, Online Co-..."
1,1645820,Roadmap Miscellaneous Updates: More map update...,Zurvivor,No DLC,"Action, Adventure, Indie, RPG, Early Access",https://shared.akamai.steamstatic.com/store_it...,SurrounDead,11.99,PlaySurrounDead,"Jun 24, 2022",...,Englishlanguages with full audio support,Indie_Action,19,14608,1930,22234,24164,https://store.steampowered.com/app/1645820/,None,"Single-player, Steam Achievements, Steam Tradi..."
2,1062520,Community Join Dinkum's official Discord! Show...,James Bendon,2468700,"Adventure, Casual, Indie, RPG, Simulation",https://shared.akamai.steamstatic.com/store_it...,Dinkum,15.99,"KRAFTON, Inc.","Apr 22, 2025",...,"English, French, Italian, German, Russian, Spa...",Indie_RPG,122,15557,2297,26266,28563,https://store.steampowered.com/app/1062520/,https://dinkum.krafton.com,"Single-player, Multi-player, Co-op, Online Co-..."
3,683320,Gris is a hopeful young girl lost in her own w...,Nomada Studio,986250,"Adventure, Indie",https://shared.akamai.steamstatic.com/store_it...,GRIS,14.99,Devolver Digital,"Dec 13, 2018",...,"English, French, German, Spanish - Spain, Japa...",Indie_Platformer,1625,26616,3674,90384,94058,https://store.steampowered.com/app/683320/,http://www.nomada.studio,"Single-player, Steam Achievements, Full contro..."
4,1295920,Having completed your degree in mortuary scien...,DarkStone Digital,2080860,"Adventure, Indie, Simulation",https://shared.akamai.steamstatic.com/store_it...,The Mortuary Assistant,24.99,DreadXP,"Aug 2, 2022",...,"English, French, Portuguese - Brazil, Italian,...",Indie_Horror,1667,4674,690,7801,8491,https://store.steampowered.com/app/1295920/,None,"Single-player, Steam Achievements, Full contro..."

In [23]:
print(games_data.shape)
games_data.info()

(660, 22)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660 entries, 0 to 659
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   app_id                 660 non-null    int64
 1   description            660 non-null    object
 2   developers             660 non-null    object
 3   dlc_app_ids            660 non-null    object
 4   genres                 660 non-null    object
 5   header_image           660 non-null    object
 6   name                   660 non-null    object
 7   price                  660 non-null    float64
 8   publishers             660 non-null    object
 9   release_date           660 non-null    object
 10  review_summary         660 non-null    object
 11  short_description      660 non-null    object
 12  supported_languages    660 non-null    object
 13  tag                    660 non-null    object
 14  tag_id                 660 non-null    int64
 15  total_english_reviews  660 non-null    int64
 16  total_negative         660 non-null    int64
 17  total_positive         660 non-null    int64
 18  total_reviews          660 non-null    int64
 19  url                    660 non-null    object
 20  website                482 non-null    object
 21  features               660 non-null    object
dtypes: float64(1), int64(6), object(15)
memory usage: 113.6+ KB

In [24]:
games_data.isna().sum()

app_id                     0
description                0
developers                 0
dlc_app_ids                0
genres                     0
header_image               0
name                       0
price                      0
publishers                 0
release_date               0
review_summary             0
short_description          0
supported_languages        0
tag                        0
tag_id                     0
total_english_reviews      0
total_negative             0
total_positive             0
total_reviews              0
url                        0
website                  178
features                   0
dtype: int64

In [25]:
dlcs_data =pd.read_json('cleaned_DLCS_data (1).json',lines=True)
dlcs_data

,app_id,description,developers,genres,header_image,name,parent_app_id,price,publishers,release_date,...,supported_languages,tag,tag_id,total_english_reviews,total_negative,total_positive,total_reviews,url,website,features
0,939480,The Slime Rancher: VR Playground is a standalo...,"Monomi Park, 3lb Games","Action, Adventure, Indie, Simulation",https://shared.akamai.steamstatic.com/store_it...,Slime Rancher: VR Playground,433340,0.00,,"Nov 14, 2018",...,English,Indie_Adventure,21,0,130,241,371,https://store.steampowered.com/app/939480/,http://slimerancher.com,"Single-player, Downloadable Content, VR Suppor..."
1,1079180,Discover the secret styles of all your favorit...,Monomi Park,"Action, Adventure, Indie, Simulation",https://shared.akamai.steamstatic.com/store_it...,Slime Rancher: Secret Style Pack,433340,4.79,,"Jun 18, 2019",...,"English, French, German, Spanish - Spain, Russ...",Indie_Adventure,21,0,23,453,476,https://store.steampowered.com/app/1079180/,http://slimerancher.com,"Single-player, Downloadable Content, Steam Ach..."
2,3246790,The Great Alps is an expansion to Peaks of Yor...,Anders Grube Jensen,"Action, Adventure, Indie",https://shared.akamai.steamstatic.com/store_it...,Peaks of Yore - The Great Alps,2236070,3.89,TraipseWare,"Nov 14, 2024",...,Englishlanguages with full audio support,Indie_Platformer,1625,0,31,177,208,https://store.steampowered.com/app/3246790/,https://www.peaksofyore.net/,"Single-player, Downloadable Content, Full cont..."
3,924490,"Play A Hat in Time split-screen with a friend,...",Gears for Breakfast,"Adventure, Indie",https://shared.akamai.steamstatic.com/store_it...,A Hat in Time - Co-op,253230,0.00,Gears for Breakfast,"Sep 17, 2018",...,"English, Germanlanguages with full audio support",Indie_Platformer,1625,0,0,3,3,https://store.steampowered.com/app/924490/,http://hatintime.com/,"Single-player, Shared/Split Screen Co-op, Down..."
4,969710,You know how you have that one annoying friend...,Team Meat,Indie,https://shared.akamai.steamstatic.com/store_it...,Super Meat Boy Race Mode,40800,4.99,Team Meat,"Oct 24, 2018",...,"English, Russian",Indie_Platformer,1625,0,62,36,98,https://store.steampowered.com/app/969710/,http://www.supermeatboy.com,"Single-player, Downloadable Content, Full cont..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
653,2246730,Transform your ball with supernatural energy a...,Team17,"Casual, Indie, Sports",https://shared.akamai.steamstatic.com/store_it...,Golf With Your Friends - Horrifying Headgear Pack,431240,1.35,Team17,"May 18, 2023",...,"English, French, Italian, German, Spanish - Sp...",Rescrape,0,0,2,9,11,https://store.steampowered.com/app/2246730/,https://www.team17.com/,"Single-player, Multi-player, PvP, Online PvP, ..."
654,1277570,Turn the fairway into a runway and customise y...,Blacklight Interactive,"Casual, Indie, Sports",https://shared.akamai.steamstatic.com/store_it...,Golf With Your Friends - Caddy Pack,431240,1.35,Team17 Digital,"May 26, 2020",...,"English, French, Italian, German, Spanish - Sp...",Rescrape,0,0,19,101,120,https://store.steampowered.com/app/1277570/,https://www.team17.com/,"Single-player, Multi-player, PvP, Online PvP, ..."
655,3041150,Honour the storied past of the Gingy's homelan...,Team17,"Casual, Indie, Sports",https://shared.akamai.steamstatic.com/store_it...,Golf With Your Friends - Legends of Olympus Pack,431240,1.35,Team17,"Sep 5, 2024",...,"English, French, Italian, German, Spanish - Sp...",Rescrape,0,0,0,3,3,https://store.steampowered.com/app/3041150/,https://www.gwyf.golf/,"Single-player, Multi-player, PvP, Online PvP, ..."
656,1901922,Master the colourful hazards of the new Bouncy...,"Blacklight Interactive, Team17","Casual, Indie, Sports",https://shared.akamai.steamstatic.com/store_it...,Golf With Your Friends - Bouncy Castle Course,431240,2.24,Team17,"Jun 21, 2022",...,"English, French, Italian, German, Spanish - Sp...",Rescrape,0,0,91,106,197,https://store.steampowered.com/app/1901922/,https://www.team17.com/games/golf-with-your-fr...,"Single-player, Multi-player, PvP, Online PvP, ..."
657,2366470,An unusual meteor strike has seeped corruption...,Team17,"Casual, Indie, Sports",https://shared.akamai.steamstatic.com/store_it...,Golf With Your Friends - Corrupted Forest Course,431240,1.24,Team17,"May 18, 2023",...,"English, French, Italian, German, Spanish - Sp...",Rescrape,0,0,446,102,548,https://store.steampowered.com/app/2366470/,https://www.team17.com/,"Single-player, Multi-player, PvP, Online PvP, ..."

In [26]:
dlcs_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 658 entries, 0 to 657
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   app_id                 658 non-null    int64
 1   description            658 non-null    object
 2   developers             658 non-null    object
 3   genres                 658 non-null    object
 4   header_image           658 non-null    object
 5   name                   658 non-null    object
 6   parent_app_id          658 non-null    int64
 7   price                  658 non-null    float64
 8   publishers             658 non-null    object
 9   release_date           658 non-null    object
 10  review_summary         658 non-null    object
 11  short_description      658 non-null    object
 12  supported_languages    658 non-null    object
 13  tag                    658 non-null    object
 14  tag_id                 658 non-null    int64
 15  total_english_reviews  658 non-null    int64
 16  total_negative         658 non-null    int64
 17  total_positive         658 non-null    int64
 18  total_reviews          658 non-null    int64
 19  url                    658 non-null    object
 20  website                609 non-null    object
 21  features               658 non-null    object
dtypes: float64(1), int64(7), object(14)
memory usage: 113.2+ KB

In [27]:
reviews_data=pd.read_json('reviews_data_cleaned.json',lines=True)
reviews_data

,app_id,parent_app_id,recommendationid,recommendation,review_text,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,received_for_free,written_during_early_access
0,3669570,3669570,223875804,Recommended,Really fun actually Just like a little factori...,positive,10.7,10.7,0,False,False,True
1,3669570,3669570,219038522,Recommended,Just spent 2 hours on making a semicompact cok...,positive,70.2,70.2,0,True,False,True
2,3669570,3669570,223815953,Recommended,I have been taking my time wthis gamemaking bl...,positive,1376.0,1364.8,0,True,False,True
3,3669570,3669570,223710270,Not Recommended,Looks like a fun game but holy the belt placem...,negative,2.3,2.3,2,True,False,True
4,3669570,3669570,223641705,Recommended,I like automation games Factorio Satisfactory ...,positive,39.0,5.0,0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
19486,418370,418370,223809604,Recommended,The game that saved the Resident Evil series b...,positive,11.8,11.8,0,True,False,False
19487,418370,418370,223806355,Recommended,this game is so peak if ur thinking of buying ...,positive,33.6,29.6,1,True,False,False
19488,418370,418370,223800427,Recommended,Jogo muito bom para os acostumados com a franq...,positive,14.6,13.1,0,True,False,False
19489,418370,418370,223799141,Recommended,Was told this was the most Accurate for Riside...,positive,9.3,5.0,0,True,False,False
19490,418370,418370,223782005,Recommended,DAMM best game ever so interesting we need mor...,positive,15.4,15.0,0,True,False,False

In [28]:
reviews_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19491 entries, 0 to 19490
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   app_id                       19491 non-null  int64
 1   parent_app_id                19491 non-null  int64
 2   recommendationid             19491 non-null  int64
 3   recommendation               19491 non-null  object
 4   review_text                  19491 non-null  object
 5   review_score                 19491 non-null  object
 6   total_playtime_hours         19491 non-null  float64
 7   playtime_at_review_hours     19491 non-null  float64
 8   votes_up                     19491 non-null  int64
 9   steam_purchase               19491 non-null  bool
 10  received_for_free            19491 non-null  bool
 11  written_during_early_access  19491 non-null  bool
dtypes: bool(3), float64(2), int64(4), object(3)
memory usage: 1.4+ MB

# ***Preprocessing***

In [29]:
enc=LabelEncoder()
data=enc.fit_transform(games_data['review_summary'])

In [30]:
dict(zip(enc.classes_, enc.transform(enc.classes_)))

{'': np.int64(0),
 '6 user reviews': np.int64(1),
 '8 user reviews': np.int64(2),
 '9 user reviews': np.int64(3),
 'Mixed': np.int64(4),
 'Mostly Negative': np.int64(5),
 'Mostly Positive': np.int64(6),
 'Overwhelmingly Positive': np.int64(7),
 'Positive': np.int64(8),
 'Very Positive': np.int64(9)}

In [31]:
games_data.drop(['description','developers','header_image','publishers','short_description','total_english_reviews','url','website'],axis=1 , inplace=True)

In [32]:
genre_stats=games_data.groupby('tag').agg({
'price':'mean',
'total_positive':'sum',
'total_negative':'sum'
})

In [33]:
fig = px.imshow(
    genre_stats,
    color_continuous_scale='viridis',
    text_auto=True,  # This adds annotations with the values
    aspect="auto",   # Maintains aspect ratio
    height=800,      # Equivalent to figsize=(20,20) in matplotlib
    width=800
)
fig.update_layout(
    title="Genre Statistics Heatmap",
    coloraxis_colorbar=dict(title="Value"),
    font=dict(size=12)
)


fig.show()

# **What are the tags have postive and negative reviews?**

In [34]:
fig2 = px.bar(
    data_frame=games_data.groupby('tag')['total_positive'].sum().reset_index(),
    x='tag',
    y='total_positive',
    title='Positive Reviews',
    labels={'tag': 'Tag', 'total_positive': 'Total Positive'},
    color='tag',
    color_discrete_sequence=px.colors.qualitative.Bold,
    height=800,
    width=1200
)


fig2.update_layout(
    xaxis_title='tag',
    yaxis_title='total_positive',
    showlegend=False,
    font=dict(size=14)
)


fig2.update_xaxes(tickangle=45)
fig2.show()

In [35]:
fig3 = px.bar(
    data_frame=games_data.groupby('tag')['total_negative'].sum().reset_index(),
    x='tag',
    y='total_negative',
    title='Negative Reviews',
    labels={'tag': 'Tag', 'total_positive': 'Total Positive'},
    color='tag',
    color_discrete_sequence=px.colors.qualitative.Bold,
    height=800,
    width=1200
)


fig3.update_layout(
    xaxis_title='tag',
    yaxis_title='total_negative',
    showlegend=False,
    font=dict(size=14)
)


fig3.update_xaxes(tickangle=45)
fig3.show()

# **What is the profit(average value, not real data from  steam) for each Tag and analysis for that?**

In [36]:
tags = games_data['tag'].str.get_dummies(';')

In [37]:
games_data['positive_pct'] = (
games_data['total_positive'] /
games_data['total_reviews']
) * 100

In [38]:
games_data['negative_pct'] = (
games_data['total_negative'] /
games_data['total_reviews']
) * 100

In [39]:
results = []

for tag_name in tags.columns:

    mask = (tags[tag_name] == 1)
    tagged_games = games_data.loc[mask]


    if tagged_games.empty:
        continue


    results.append({
        'tag': tag_name,
        'positive%': tagged_games['positive_pct'].mean().round(2),
        'negative%': tagged_games['negative_pct'].mean().round(2),
        'avg_price': tagged_games['price'].mean().round(2),
        'Total Reviews': tagged_games['total_reviews'].sum(),
        'Game Count': len(tagged_games)
    })


tag_df = pd.DataFrame(results)


tag_df = tag_df.sort_values('Total Reviews', ascending=False).reset_index(drop=True)

In [40]:
tag_df['Average Profit (M)']=((tag_df['avg_price']*tag_df['Total Reviews']*0.4)/1000000).round(2)  ## Assume profit is 40% of total price
tag_df['Average Profit per game (M)']=(tag_df['Average Profit (M)']/tag_df['Game Count']).round(2)

In [41]:
tag_df

,tag,positive%,negative%,avg_price,Total Reviews,Game Count,Average Profit (M),Average Profit per game (M)
0,AAA_Action,80.99,19.01,14.59,27120886,53,158.28,2.99
1,Indie_Action,88.92,11.08,17.15,10289129,80,70.58,0.88
2,Indie_Adventure,88.18,11.82,15.81,1806806,28,11.43,0.41
3,Indie_FPS,86.74,13.26,13.72,1777977,67,9.76,0.15
4,Indie_RPG,87.84,12.16,16.82,1405857,40,9.46,0.24
5,Indie_Horror,89.58,10.42,13.19,1364313,59,7.20,0.12
6,AAA_Simulation,72.55,27.45,33.95,1289571,18,17.51,0.97
7,Indie_Platformer,93.12,6.88,13.74,1087286,67,5.98,0.09
8,Indie_Simulation,91.16,8.84,16.90,1076641,25,7.28,0.29
9,Indie_Survival,85.21,14.79,15.33,942453,37,5.78,0.16
10,Indie_Casual,90.08,9.92,12.07,788714,50,3.81,0.08
11,Indie_Puzzle,92.37,7.63,13.40,763577,43,4.09,0.10
12,Indie_Strategy,88.26,11.74,13.29,598284,45,3.18,0.07
13,AAA_RPG,81.54,18.46,17.43,572348,9,3.99,0.44
14,Indie_Open World,86.41,13.59,16.29,343774,29,2.24,0.08
15,AAA_Adventure,86.65,13.35,22.19,290356,6,2.58,0.43
16,AAA_Racing,72.22,27.78,26.32,43384,3,0.46,0.15
17,AAA_Early Access,97.93,2.07,11.24,9317,1,0.04,0.04

In [42]:
sorted_df = tag_df.sort_values('Average Profit (M)', ascending=False)

# Create a figure with subplots
fig4 = make_subplots(
    rows=2, cols=2,
    specs=[[{"type": "bar"}, {"type": "scatter"}],
           [{"type": "bar", "colspan": 2}, None]],
    subplot_titles=("Average Profit by Tag (Millions $)",
                   "Profit vs. Review Sentiment",
                   "Average Profit per Game by Tag (Millions $)"),
    vertical_spacing=0.12,
    horizontal_spacing=0.08
)

# 1. Bar chart for Average Profit by Tag
fig4.add_trace(
    go.Bar(
        x=sorted_df['tag'],
        y=sorted_df['Average Profit (M)'],
        marker_color=sorted_df['positive%'],
        marker_colorbar=dict(title="Positive %"),
        marker_colorscale='RdYlGn',
        text=sorted_df['Average Profit (M)'].apply(lambda x: f"${x:.1f}M"),
        textposition='auto',
        name='Total Profit'
    ),
    row=1, col=1
)

# 2. Scatter plot for Profit vs Sentiment with size as Total Reviews
fig4.add_trace(
    go.Scatter(
        x=sorted_df['positive%'],
        y=sorted_df['Average Profit (M)'],
        mode='markers',
        marker=dict(
            size=sorted_df['Total Reviews'].apply(lambda x: min(max(x/10000, 10), 50)),
            color=sorted_df['avg_price'],
            colorscale='Viridis',
            colorbar=dict(title="Avg Price ($)"),
            showscale=True
        ),
        text=sorted_df['tag'],
        hovertemplate='<b>%{text}</b><br>Positive: %{x:.1f}%<br>Profit: $%{y:.1f}M<br>Reviews: %{marker.size}<br>Avg Price: $%{marker.color:.2f}<extra></extra>',
        name='Tag Performance'
    ),
    row=1, col=2
)

# 3. Bar chart for Average Profit per Game
fig4.add_trace(
    go.Bar(
        x=sorted_df['tag'],
        y=sorted_df['Average Profit per game (M)'],
        marker_color=sorted_df['Game Count'],
        marker_colorscale='Blues',
        marker_colorbar=dict(title="Game Count"),
        text=sorted_df['Average Profit per game (M)'].apply(lambda x: f"${x:.2f}M"),
        textposition='auto',
        name='Profit per Game'
    ),
    row=2, col=1
)

# Update layout
fig4.update_layout(
    title_text="Game Tag Performance Analysis",
    height=900,
    width=1200,
    template="plotly_white",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    font=dict(family="Arial", size=12)
)

# Update axes
fig4.update_xaxes(tickangle=45, row=1, col=1)
fig4.update_xaxes(tickangle=45, row=2, col=1)
fig4.update_xaxes(title_text="Positive Reviews (%)", row=1, col=2)
fig4.update_yaxes(title_text="Average Profit (Millions $)", row=1, col=1)
fig4.update_yaxes(title_text="Average Profit (Millions $)", row=1, col=2)
fig4.update_yaxes(title_text="Average Profit per Game (Millions $)", row=2, col=1)

# Show the figure
fig4.show()

# How many games are released each year?

In [43]:
games_data['release_date'] = pd.to_datetime(games_data['release_date'], format='%b %d, %Y')
games_data

,app_id,dlc_app_ids,genres,name,price,release_date,review_summary,supported_languages,tag,tag_id,total_negative,total_positive,total_reviews,features,positive_pct,negative_pct
0,3669570,No DLC,"Casual, Indie, Simulation, Strategy, Early Access",Alchemy Factory,16.19,2025-12-11,Very Positive,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694
1,1645820,No DLC,"Action, Adventure, Indie, RPG, Early Access",SurrounDead,11.99,2022-06-24,Very Positive,Englishlanguages with full audio support,Indie_Action,19,1930,22234,24164,"Single-player, Steam Achievements, Steam Tradi...",92.012912,7.987088
2,1062520,2468700,"Adventure, Casual, Indie, RPG, Simulation",Dinkum,15.99,2025-04-22,Very Positive,"English, French, Italian, German, Russian, Spa...",Indie_RPG,122,2297,26266,28563,"Single-player, Multi-player, Co-op, Online Co-...",91.958128,8.041872
3,683320,986250,"Adventure, Indie",GRIS,14.99,2018-12-13,Very Positive,"English, French, German, Spanish - Spain, Japa...",Indie_Platformer,1625,3674,90384,94058,"Single-player, Steam Achievements, Full contro...",96.093900,3.906100
4,1295920,2080860,"Adventure, Indie, Simulation",The Mortuary Assistant,24.99,2022-08-02,Very Positive,"English, French, Portuguese - Brazil, Italian,...",Indie_Horror,1667,690,7801,8491,"Single-player, Steam Achievements, Full contro...",91.873749,8.126251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,3059520,"3493820, 3335220","Racing, Simulation, Sports",F1® 25,23.99,2025-05-30,Very Positive,"English, French, Italian, German, Spanish - Sp...",AAA_Simulation,599,3050,20889,23939,"Single-player, Multi-player, PvP, Online PvP, ...",87.259284,12.740716
656,1435790,"3972570, 2644890, 2419810, 2175260, 1942100, 3...","Adventure, Casual, Indie, Simulation",Escape Simulator,19.99,2021-10-19,Overwhelmingly Positive,"English, Japanese, Korean, Simplified Chinese,...",Indie_Adventure,21,1149,17817,18966,"Single-player, Multi-player, PvP, Online PvP, ...",93.941791,6.058209
657,313120,1492970,"Adventure, Indie",Stranded Deep,19.99,2022-08-10,Mostly Positive,"English, French, Italian, German, Spanish - Sp...",Indie_Adventure,21,12085,35090,47175,"Single-player, Multi-player, Co-op, Online Co-...",74.382618,25.617382
658,285900,1003800,"Action, Adventure, Casual, Indie, Simulation",Gang Beasts,7.99,2017-12-12,Very Positive,"English, French, Italian, German, Spanish - Sp...",Indie_Action,19,9388,54926,64314,"Multi-player, PvP, Online PvP, Shared/Split Sc...",85.402867,14.597133
659,418370,"564190, 530611, 540340, 529930, 530610, 583810","Action, Adventure",Resident Evil 7 Biohazard,19.99,2017-01-23,Very Positive,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541

In [44]:
games_data['year'] = games_data['release_date'].dt.year

# Count number of games per year
games_per_year = games_data.groupby('year').size().reset_index(name='count')

In [45]:
fig5 = px.line(games_per_year,
              x='year',
              y='count',
              title='Number of Games Released Each Year',
              labels={'year': 'Year', 'count': 'Number of Games'},
              markers=True)  # Add markers to the line


fig5.update_layout(
    xaxis=dict(tickmode='linear'),  # Show all years
    yaxis=dict(title='Number of Games'),
    hovermode='x unified',
    height=600
)


fig5.show()

In [46]:
reviews_data.drop(['recommendationid','review_text','received_for_free'],axis=1 , inplace=True)

# **Now what are the features & genres and tags prefered (with details)?**

In [47]:
encoded_reviews_data = reviews_data.copy()  # Create a copy to avoid modifying the original data


encoder = LabelEncoder()
columns_to_encode = ['recommendation', 'review_score', 'steam_purchase', 'written_during_early_access']

for column in columns_to_encode:
    # Check if column exists and contains non-numeric data that needs encoding
    if column in encoded_reviews_data.columns:
        encoded_reviews_data[column] = encoder.fit_transform(encoded_reviews_data[column])

In [48]:
encoded_reviews_data

,app_id,parent_app_id,recommendation,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,written_during_early_access
0,3669570,3669570,1,1,10.7,10.7,0,0,1
1,3669570,3669570,1,1,70.2,70.2,0,1,1
2,3669570,3669570,1,1,1376.0,1364.8,0,1,1
3,3669570,3669570,0,0,2.3,2.3,2,1,1
4,3669570,3669570,1,1,39.0,5.0,0,1,1
...,...,...,...,...,...,...,...,...,...
19486,418370,418370,1,1,11.8,11.8,0,1,0
19487,418370,418370,1,1,33.6,29.6,1,1,0
19488,418370,418370,1,1,14.6,13.1,0,1,0
19489,418370,418370,1,1,9.3,5.0,0,1,0
19490,418370,418370,1,1,15.4,15.0,0,1,0

In [49]:
merged_data = encoded_reviews_data.merge(
    games_data,
    left_on='parent_app_id',
    right_on='app_id',
    how='left',
    suffixes=('_review', '_game')
)

In [50]:
merged_data

,app_id_review,parent_app_id,recommendation,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,written_during_early_access,app_id_game,...,supported_languages,tag,tag_id,total_negative,total_positive,total_reviews,features,positive_pct,negative_pct,year
0,3669570,3669570,1,1,10.7,10.7,0,0,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
1,3669570,3669570,1,1,70.2,70.2,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
2,3669570,3669570,1,1,1376.0,1364.8,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
3,3669570,3669570,0,0,2.3,2.3,2,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
4,3669570,3669570,1,1,39.0,5.0,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19486,418370,418370,1,1,11.8,11.8,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19487,418370,418370,1,1,33.6,29.6,1,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19488,418370,418370,1,1,14.6,13.1,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19489,418370,418370,1,1,9.3,5.0,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19490,418370,418370,1,1,15.4,15.0,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0

In [51]:
# 2. Most Popular features
# Assuming features are in a column or need to be extracted
# If features are in a list format in a single column, we need to explode them first
if 'features' in games_data.columns:
    # Check if categories need to be processed (e.g., from string to list)
    if isinstance(games_data['features'].iloc[0], str):
        games_data['features'] = games_data['features'].apply(lambda x: x.split(',') if isinstance(x, str) else x)

    # Explode categories to get one row per category
    categories_exploded = games_data.explode('features')


    category_counts = categories_exploded['features'].value_counts().reset_index()
    category_counts.columns = ['features', 'count']


    fig7 = px.bar(
        category_counts.head(10),
        x='features',
        y='count',
        title='Top 10 Game Features',
        labels={'features': 'Features', 'count': 'Number of Games'},
        color='count',
        color_continuous_scale='Reds',
        height=800

    )
    fig7.update_layout(xaxis_tickangle=-45)
    fig7.show()

### Genres by Number of Games

This table shows each unique genre and the total number of games that include that genre. It gives an idea of the prevalence of each genre in the dataset.

### Average Positive Review Percentage by Genre

In [52]:
games_data['positive_pct'] = (
games_data['total_positive'] /
games_data['total_reviews']
) * 100
games_data['negative_pct'] = (
games_data['total_negative'] /
games_data['total_reviews']
) * 100

# Define a cleaning function to ensure consistency (duplicate for robustness if cell 4U8mE4yW7WMv isn't run first)
def clean_genre_entry_for_d6c31f62(entry):
    if isinstance(entry, str):
        return [g.strip().lower() for g in entry.split(',')]
    elif isinstance(entry, list):
        return [g.strip().lower() for g in entry if isinstance(g, str)]
    return []

# Apply the cleaning function to the genres column to ensure consistency
games_data['genres'] = games_data['genres'].apply(clean_genre_entry_for_d6c31f62)

genres_and_reviews = games_data.explode('genres')

# Filter out any empty strings that might have resulted from cleaning
genres_and_reviews = genres_and_reviews[genres_and_reviews['genres'] != '']

# Calculate the total positive reviews for each genre
genre_positive_reviews = genres_and_reviews.groupby('genres')['total_positive'].sum().reset_index()
genre_positive_reviews = genre_positive_reviews.sort_values('total_positive', ascending=False)
genre_positive_reviews = genre_positive_reviews.drop(genre_positive_reviews[genre_positive_reviews['genres'] == 'indie'].index)

display(genre_positive_reviews)

                   genres  total_positive
0                  action        34484212
4            free to play        18805945
1               adventure        16631222
9              simulation        11223909
8                     rpg         7498863
12               strategy         6537080
2                  casual         5546631
6   massively multiplayer         4119686
3            early access         3824996
7                  racing         1199024
11                 sports          835494
13              utilities           44172
10      software training           38297

In [53]:
fig_avg_positive = px.bar(
    genre_positive_reviews,
    x='total_positive',
    y='genres',
    orientation='h',
    title='Average Positive Review Percentage by Genre',
    labels={'total_positive': ' Positive Review %', 'genres': 'Genre'},
    color='total_positive',
    color_continuous_scale='Greens',
    height=800
)

fig_avg_positive.update_layout(
    yaxis={'categoryorder': 'total ascending'},
    xaxis_title='Postive Percentage'
)
fig_avg_positive.show()

In [110]:
# 3. Most Popular Tags (similar approach as categories)
# Explode tags to get one row per tag
tag_exploded = games_data.explode('tag')

tag_counts = tag_exploded['tag'].value_counts().reset_index()
tag_counts.columns = ['tag', 'count']


fig8 = px.bar(
    tag_counts.head(15),
    x='tag',
    y='count',
    title='Top 15 Game Tags',
    labels={'tag': 'Tag', 'count': 'Number of Games'},
    color='count',
    color_continuous_scale='Blues',
    height=800

)
fig8.update_layout(xaxis_tickangle=-45)
fig8.show()

### Features by Genre

This section visualizes the top features associated with each game genre. Each bar chart shows the most frequent features for a specific genre, providing insight into what functionalities or characteristics are commonly found in games belonging to that genre.

In [55]:
merged_games_2=games_data.copy()

In [56]:
# Explode both genres and features from merged_games_2
exploded_genre_features = merged_games_2.explode('genres')
exploded_genre_features = exploded_genre_features.explode('features')

# Clean up feature strings (remove leading/trailing whitespace)
exploded_genre_features['features'] = exploded_genre_features['features'].str.strip()

# Count features per genre
genre_feature_counts = exploded_genre_features.groupby(['genres', 'features']).size().reset_index(name='count')

# Get unique genres to iterate through
unique_genres = genre_feature_counts['genres'].unique()

# Create a bar chart for each genre showing its top features
for genre in unique_genres:
    genre_df = genre_feature_counts[genre_feature_counts['genres'] == genre]
    # Get top 10 features for each genre
    top_features = genre_df.sort_values('count', ascending=False).head(10)

    if not top_features.empty:
        fig = px.bar(
            top_features,
            x='count',
            y='features',
            orientation='h',
            title=f'Top Features for Genre: {genre.title()}',
            labels={'count': 'Number of Games', 'features': 'Feature'},
            color='count',
            color_continuous_scale='Viridis',
            height=600
        )
        fig.update_layout(yaxis={'categoryorder': 'total ascending'})
        fig.show()

# **What the languages should i put in my game?**

In [57]:
# 1. Most Used Languages Visualization
if 'supported_languages' in games_data.columns:
    # Process the comma-separated language strings
    all_languages = []

    # Extract all languages from the comma-separated strings
    for lang_str in games_data['supported_languages'].dropna():
        languages = [lang.strip() for lang in lang_str.split(',')]
        all_languages.extend(languages)

    # Count frequency of each language
    language_counts = Counter(all_languages)
    top_languages = pd.DataFrame({
        'language': list(dict(language_counts.most_common(10)).keys()),
        'count': list(dict(language_counts.most_common(10)).values())
    })

    # Create horizontal bar chart with Plotly
    fig9 = px.bar(
        top_languages,
        x='count',
        y='language',
        orientation='h',
        title='Top 10 Most Used Languages',
        labels={'count': 'Number of Games', 'language': 'Language'},
        color='count',
        color_continuous_scale='Viridis',
        height=800
    )

    # Improve layout
    fig9.update_layout(
        height=800,
        width=900,
        xaxis_title='Number of Games',
        yaxis_title='Language',
        yaxis={'categoryorder': 'total ascending'},  # Sort bars by value
        title_font={'size': 20},
        font=dict(size=14)
    )

    # Add text labels on bars
    fig9.update_traces(texttemplate='%{x}', textposition='outside')

    fig9.show()
else:
    print("No 'supported_languages' column found in the data")

# **I want to know the profit from steam questionare , and how the price affects number of sales**

In [58]:
merged_data

,app_id_review,parent_app_id,recommendation,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,written_during_early_access,app_id_game,...,supported_languages,tag,tag_id,total_negative,total_positive,total_reviews,features,positive_pct,negative_pct,year
0,3669570,3669570,1,1,10.7,10.7,0,0,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
1,3669570,3669570,1,1,70.2,70.2,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
2,3669570,3669570,1,1,1376.0,1364.8,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
3,3669570,3669570,0,0,2.3,2.3,2,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
4,3669570,3669570,1,1,39.0,5.0,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19486,418370,418370,1,1,11.8,11.8,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19487,418370,418370,1,1,33.6,29.6,1,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19488,418370,418370,1,1,14.6,13.1,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19489,418370,418370,1,1,9.3,5.0,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19490,418370,418370,1,1,15.4,15.0,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0

In [59]:
purchased_data=merged_data[['parent_app_id','steam_purchase']]

In [60]:
purchased_data

       parent_app_id  steam_purchase
0            3669570               0
1            3669570               1
2            3669570               1
3            3669570               1
4            3669570               1
...              ...             ...
19486         418370               1
19487         418370               1
19488         418370               1
19489         418370               1
19490         418370               1

[19491 rows x 2 columns]

In [61]:
purchased_data = merged_data[['parent_app_id','steam_purchase']]
purchased_data = purchased_data.groupby('parent_app_id')['steam_purchase'].sum().reset_index()

# Rename columns for clarity
purchased_data.columns = ['parent_app_id', 'total_steam_purchases']

# Sort by total purchases in descending order (optional)
purchased_data = purchased_data.sort_values('total_steam_purchases', ascending=False)
purchased_data

     parent_app_id  total_steam_purchases
657        4286550                     30
634        3983810                     30
22          216150                     30
30          230410                     30
33          236090                     30
..             ...                    ...
433        2232880                      5
407        1967220                      3
162         613100                      3
592        3513600                      3
599        3568460                      1

[660 rows x 2 columns]

In [62]:
merged_games_2= games_data.merge(
    purchased_data,
    left_on='app_id',
    right_on='parent_app_id',
    how='left',
)
merged_data

,app_id_review,parent_app_id,recommendation,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,written_during_early_access,app_id_game,...,supported_languages,tag,tag_id,total_negative,total_positive,total_reviews,features,positive_pct,negative_pct,year
0,3669570,3669570,1,1,10.7,10.7,0,0,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
1,3669570,3669570,1,1,70.2,70.2,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
2,3669570,3669570,1,1,1376.0,1364.8,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
3,3669570,3669570,0,0,2.3,2.3,2,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
4,3669570,3669570,1,1,39.0,5.0,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19486,418370,418370,1,1,11.8,11.8,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19487,418370,418370,1,1,33.6,29.6,1,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19488,418370,418370,1,1,14.6,13.1,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19489,418370,418370,1,1,9.3,5.0,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19490,418370,418370,1,1,15.4,15.0,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0

In [63]:
merged_games_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660 entries, 0 to 659
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   app_id                 660 non-null    int64
 1   dlc_app_ids            660 non-null    object
 2   genres                 660 non-null    object
 3   name                   660 non-null    object
 4   price                  660 non-null    float64
 5   release_date           659 non-null    datetime64[ns]
 6   review_summary         660 non-null    object
 7   supported_languages    660 non-null    object
 8   tag                    660 non-null    object
 9   tag_id                 660 non-null    int64
 10  total_negative         660 non-null    int64
 11  total_positive         660 non-null    int64
 12  total_reviews          660 non-null    int64
 13  features               660 non-null    object
 14  positive_pct           659 non-null    float64
 15  negative_pct           659 non-null    float64
 16  year                   659 non-null    float64
 17  parent_app_id          660 non-null    int64
 18  total_steam_purchases  660 non-null    int64
dtypes: datetime64[ns](1), float64(4), int64(7), object(7)
memory usage: 98.1+ KB

In [64]:
merged_games_2.drop(['dlc_app_ids','release_date','supported_languages','tag_id','year'],axis=1,inplace=True)

In [65]:
merged_games_2

,app_id,genres,name,price,review_summary,tag,total_negative,total_positive,total_reviews,features,positive_pct,negative_pct,parent_app_id,total_steam_purchases
0,3669570,"[casual, indie, simulation, strategy, early ac...",Alchemy Factory,16.19,Very Positive,Indie_Strategy,217,1996,2213,"[Single-player, Multi-player, Co-op, Online...",90.194306,9.805694,3669570,21
1,1645820,"[action, adventure, indie, rpg, early access]",SurrounDead,11.99,Very Positive,Indie_Action,1930,22234,24164,"[Single-player, Steam Achievements, Steam Tr...",92.012912,7.987088,1645820,28
2,1062520,"[adventure, casual, indie, rpg, simulation]",Dinkum,15.99,Very Positive,Indie_RPG,2297,26266,28563,"[Single-player, Multi-player, Co-op, Online...",91.958128,8.041872,1062520,22
3,683320,"[adventure, indie]",GRIS,14.99,Very Positive,Indie_Platformer,3674,90384,94058,"[Single-player, Steam Achievements, Full con...",96.093900,3.906100,683320,26
4,1295920,"[adventure, indie, simulation]",The Mortuary Assistant,24.99,Very Positive,Indie_Horror,690,7801,8491,"[Single-player, Steam Achievements, Full con...",91.873749,8.126251,1295920,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,3059520,"[racing, simulation, sports]",F1® 25,23.99,Very Positive,AAA_Simulation,3050,20889,23939,"[Single-player, Multi-player, PvP, Online P...",87.259284,12.740716,3059520,26
656,1435790,"[adventure, casual, indie, simulation]",Escape Simulator,19.99,Overwhelmingly Positive,Indie_Adventure,1149,17817,18966,"[Single-player, Multi-player, PvP, Online P...",93.941791,6.058209,1435790,26
657,313120,"[adventure, indie]",Stranded Deep,19.99,Mostly Positive,Indie_Adventure,12085,35090,47175,"[Single-player, Multi-player, Co-op, Online...",74.382618,25.617382,313120,23
658,285900,"[action, adventure, casual, indie, simulation]",Gang Beasts,7.99,Very Positive,Indie_Action,9388,54926,64314,"[Multi-player, PvP, Online PvP, Shared/Spli...",85.402867,14.597133,285900,27
659,418370,"[action, adventure]",Resident Evil 7 Biohazard,19.99,Very Positive,AAA_Action,5584,113388,118972,"[Single-player, Steam Achievements, Full con...",95.306459,4.693541,418370,26

In [66]:
merged_games_2.isna().sum()

app_id                   0
genres                   0
name                     0
price                    0
review_summary           0
tag                      0
total_negative           0
total_positive           0
total_reviews            0
features                 0
positive_pct             1
negative_pct             1
parent_app_id            0
total_steam_purchases    0
dtype: int64

In [67]:
merged_games_2['Profit']=merged_games_2['price']*merged_games_2['total_steam_purchases']*0.4

In [68]:
merged_games_2['positive_ratio'] = merged_games_2['total_positive'] / merged_games_2['total_reviews']
merged_games_2['review_score'] = merged_games_2['total_positive'] - merged_games_2['total_negative']


if 'tag' in merged_games_2.columns:
    # Convert all values to string type first, then fill NaN values
    merged_games_2['tag'] = merged_games_2['tag'].astype(str)

    merged_games_2['tag'] = merged_games_2['tag'].replace('nan', '')


    merged_games_2['primary_tag'] = merged_games_2['tag'].str.split(',').str[0].str.strip()


    merged_games_2.loc[merged_games_2['primary_tag'] == '', 'primary_tag'] = None
else:

    print("Warning: 'tag' column not found in the dataframe")

In [69]:
# 1. Top 15 games by profit with tags
top_profit = merged_games_2.sort_values('Profit', ascending=False).head(15)
fig11 = px.bar(top_profit,
             x='Profit',
             y='name',
             color='primary_tag',
             hover_data=['price', 'total_reviews', 'positive_ratio'],
             title='Top 15 Games by Profit',
             labels={'name': 'Game Name', 'Profit': 'Profit ($)'},
             height=600)
fig11.update_layout(yaxis={'categoryorder':'total ascending'})
fig11.show()

In [70]:
# Function to get top N games per tag by Profit
def get_top_n_games_per_tag(df, n=3):

    filtered_df = df.dropna(subset=['primary_tag'])
    return filtered_df.groupby('primary_tag').apply(lambda x: x.nlargest(n, 'Profit')).reset_index(drop=True)


top_games_per_tag = get_top_n_games_per_tag(merged_games_2, n=3)

# Filter out rows where 'Profit' is zero or NaN to prevent ZeroDivisionError in Plotly
top_games_per_tag = top_games_per_tag[top_games_per_tag['Profit'] > 0]


fig_treemap = px.treemap(
    top_games_per_tag,
    path=[px.Constant("All Tags"), 'primary_tag', 'name'],
    values='Profit',
    color='Profit',
    color_continuous_scale='Viridis',
    title='Top 3 Games by Profit within Each Tag',
    hover_data=['Profit', 'price', 'total_reviews', 'positive_ratio']
)

fig_treemap.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig_treemap.show()

C:\Users\ALKODS\AppData\Local\Temp\ipykernel_21840\4079339037.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return filtered_df.groupby('primary_tag').apply(lambda x: x.nlargest(n, 'Profit')).reset_index(drop=True)

In [71]:
# 2. Scatter plot: Profit vs. Total Reviews with positive ratio as color
fig12 = px.scatter(merged_games_2,
                 x='total_reviews',
                 y='Profit',
                 color='positive_ratio',
                 size='price',
                 hover_name='name',
                 hover_data=['primary_tag', 'total_positive', 'total_negative'],
                 color_continuous_scale='RdYlGn',
                 title='Profit vs. Total Reviews (Color: Positive Ratio, Size: Price)',
                 labels={'total_reviews': 'Total Reviews', 'Profit': 'Profit ($)',
                        'positive_ratio': 'Positive Review Ratio'},
                 height=600)
fig12.update_layout(coloraxis_colorbar=dict(title='Positive Ratio'))
fig12.update_xaxes(type='log')
fig12.show()

In [72]:
fig13 = make_subplots(rows=1, cols=2,
                    subplot_titles=('Positive Reviews vs. Profit', 'Negative Reviews vs. Profit'))

# Positive reviews correlation
fig13.add_trace(
    go.Scatter(
        x=merged_games_2['total_positive'],
        y=merged_games_2['Profit'],
        mode='markers',
        marker=dict(
            size=8,
            color=merged_games_2['positive_ratio'],
            colorscale='RdYlGn',
            showscale=True,
            colorbar=dict(title='Positive Ratio')
        ),
        text=merged_games_2['name'] + '<br>Tag: ' + merged_games_2['primary_tag'],
        hoverinfo='text+x+y'
    ),
    row=1, col=1
)

# Negative reviews correlation
fig13.add_trace(
    go.Scatter(
        x=merged_games_2['total_negative'],
        y=merged_games_2['Profit'],
        mode='markers',
        marker=dict(
            size=8,
            color=merged_games_2['positive_ratio'],
            colorscale='RdYlGn',
            showscale=False
        ),
        text=merged_games_2['name'] + '<br>Tag: ' + merged_games_2['primary_tag'],
        hoverinfo='text+x+y'
    ),
    row=1, col=2
)

fig13.update_layout(height=500, title_text="Correlation Between Reviews and Profit")
fig13.update_xaxes(title_text="Total Positive Reviews", row=1, col=1)
fig13.update_xaxes(title_text="Total Negative Reviews", row=1, col=2)
fig13.update_yaxes(title_text="Profit ($)", row=1, col=1)
fig13.update_yaxes(title_text="Profit ($)", row=1, col=2)
fig13.show()

In [73]:
fig14 = px.scatter(
    merged_games_2,
    x='price',
    y='total_steam_purchases',

    height=800
)



fig14.show()

# **I want to the field which is less competitve**

In [74]:
all_tags = []
for tags in merged_games_2['tag']:
    if isinstance(tags, str):
        # Split tags and strip whitespace
        tag_list = [tag.strip() for tag in tags.split(',')]
        all_tags.extend(tag_list)

# Count occurrences of each tag
tag_counts = Counter(all_tags)
tag_df2 = pd.DataFrame({
    'tag': list(tag_counts.keys()),
    'game_count': list(tag_counts.values())
}).sort_values('game_count', ascending=False)

In [75]:
fig15 = px.bar(
    tag_df2.head(30),  # Top 30 tags
    x='tag',
    y='game_count',
    color='game_count',
    color_continuous_scale='Viridis',
    title='Top 30 Game Tags by Number of Games (Competition Level)',
    labels={
        'tag': 'Game Tag',
        'game_count': 'Number of Games'
    },
    height=600
)

fig15.update_layout(
    xaxis_title='Game Tag',
    yaxis_title='Number of Games',
    xaxis={'categoryorder': 'total descending'},
    coloraxis_colorbar=dict(title='Game Count')
)
fig15.update_xaxes(tickangle=45)
fig15.show()

In [76]:
tag_metrics = merged_games_2.groupby('primary_tag').agg({
    'Profit': 'mean',
    'total_steam_purchases': 'mean',
    'app_id': 'count',
    'positive_ratio': 'mean'
}).reset_index()

tag_metrics = tag_metrics.rename(columns={
    'app_id': 'game_count',
    'Profit': 'avg_profit',
    'total_steam_purchases': 'avg_purchases',
    'positive_ratio': 'avg_positive_ratio'
})
fig16 = px.scatter(
    tag_metrics[tag_metrics['game_count'] >= 5],  # Filter to tags with at least 5 games
    x='game_count',
    y='avg_profit',
    size='avg_purchases',
    color='avg_positive_ratio',
    hover_name='primary_tag',
    text='primary_tag',
    color_continuous_scale='RdYlGn',
    title='Tag Competition vs. Profitability (Size: Avg. Purchases, Color: Avg. Positive Ratio)',
    labels={
        'game_count': 'Number of Games (Competition)',
        'avg_profit': 'Average Profit ($)',
        'avg_purchases': 'Average Purchases',
        'avg_positive_ratio': 'Avg. Positive Ratio'
    },
    height=700
)

fig16.update_traces(
    textposition='top center',
    textfont=dict(size=10),
    marker=dict(line=dict(width=1, color='DarkSlateGrey'))
)
fig16.update_layout(
    xaxis_title='Number of Games (Competition Level)',
    yaxis_title='Average Profit ($)'
)
fig16.show()

# **Summary (Most important)**

In [77]:
# Calculate medians for quadrant lines
median_count = tag_metrics['game_count'].median()
median_profit = tag_metrics['avg_profit'].median()

fig17 = px.scatter(
    tag_metrics[tag_metrics['game_count'] >= 3],  # Filter to tags with at least 3 games
    x='game_count',
    y='avg_profit',
    color='avg_positive_ratio',
    size='avg_purchases',
    hover_name='primary_tag',
    text='primary_tag',
    color_continuous_scale='RdYlGn',
    title='Tag Competition vs. Profitability Quadrant Analysis',
    labels={
        'game_count': 'Number of Games (Competition)',
        'avg_profit': 'Average Profit ($)',
        'avg_positive_ratio': 'Avg. Positive Ratio'
    },
    height=700
)

# Add quadrant lines
fig17.add_shape(
    type="line", line=dict(dash="dash", width=1),
    x0=median_count, y0=0, x1=median_count, y1=tag_metrics['avg_profit'].max()*1.1
)
fig17.add_shape(
    type="line", line=dict(dash="dash", width=1),
    x0=0, y0=median_profit, x1=tag_metrics['game_count'].max()*1.1, y1=median_profit
)

# Add quadrant labels
fig17.add_annotation(x=median_count/2, y=tag_metrics['avg_profit'].max()*0.9,
            text="Low Competition<br>High Profit", showarrow=False, font=dict(size=14))
fig17.add_annotation(x=tag_metrics['game_count'].max()*0.75, y=tag_metrics['avg_profit'].max()*0.9,
            text="High Competition<br>High Profit", showarrow=False, font=dict(size=14))
fig17.add_annotation(x=median_count/2, y=median_profit/2,
            text="Low Competition<br>Low Profit", showarrow=False, font=dict(size=14))
fig17.add_annotation(x=tag_metrics['game_count'].max()*0.75, y=median_profit/2,
            text="High Competition<br>Low Profit", showarrow=False, font=dict(size=14))

fig17.update_traces(
    textposition='top center',
    textfont=dict(size=9),
    marker=dict(line=dict(width=1, color='DarkSlateGrey'))
)
fig17.update_layout(
    xaxis_title='Number of Games (Competition Level)',
    yaxis_title='Average Profit ($)'
)
fig17.show()

### Genre Competition vs. Profitability Quadrant Analysis

In [78]:
merged_games_2

,app_id,genres,name,price,review_summary,tag,total_negative,total_positive,total_reviews,features,positive_pct,negative_pct,parent_app_id,total_steam_purchases,Profit,positive_ratio,review_score,primary_tag
0,3669570,"[casual, indie, simulation, strategy, early ac...",Alchemy Factory,16.19,Very Positive,Indie_Strategy,217,1996,2213,"[Single-player, Multi-player, Co-op, Online...",90.194306,9.805694,3669570,21,135.996,0.901943,1779,Indie_Strategy
1,1645820,"[action, adventure, indie, rpg, early access]",SurrounDead,11.99,Very Positive,Indie_Action,1930,22234,24164,"[Single-player, Steam Achievements, Steam Tr...",92.012912,7.987088,1645820,28,134.288,0.920129,20304,Indie_Action
2,1062520,"[adventure, casual, indie, rpg, simulation]",Dinkum,15.99,Very Positive,Indie_RPG,2297,26266,28563,"[Single-player, Multi-player, Co-op, Online...",91.958128,8.041872,1062520,22,140.712,0.919581,23969,Indie_RPG
3,683320,"[adventure, indie]",GRIS,14.99,Very Positive,Indie_Platformer,3674,90384,94058,"[Single-player, Steam Achievements, Full con...",96.093900,3.906100,683320,26,155.896,0.960939,86710,Indie_Platformer
4,1295920,"[adventure, indie, simulation]",The Mortuary Assistant,24.99,Very Positive,Indie_Horror,690,7801,8491,"[Single-player, Steam Achievements, Full con...",91.873749,8.126251,1295920,27,269.892,0.918737,7111,Indie_Horror
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,3059520,"[racing, simulation, sports]",F1® 25,23.99,Very Positive,AAA_Simulation,3050,20889,23939,"[Single-player, Multi-player, PvP, Online P...",87.259284,12.740716,3059520,26,249.496,0.872593,17839,AAA_Simulation
656,1435790,"[adventure, casual, indie, simulation]",Escape Simulator,19.99,Overwhelmingly Positive,Indie_Adventure,1149,17817,18966,"[Single-player, Multi-player, PvP, Online P...",93.941791,6.058209,1435790,26,207.896,0.939418,16668,Indie_Adventure
657,313120,"[adventure, indie]",Stranded Deep,19.99,Mostly Positive,Indie_Adventure,12085,35090,47175,"[Single-player, Multi-player, Co-op, Online...",74.382618,25.617382,313120,23,183.908,0.743826,23005,Indie_Adventure
658,285900,"[action, adventure, casual, indie, simulation]",Gang Beasts,7.99,Very Positive,Indie_Action,9388,54926,64314,"[Multi-player, PvP, Online PvP, Shared/Spli...",85.402867,14.597133,285900,27,86.292,0.854029,45538,Indie_Action
659,418370,"[action, adventure]",Resident Evil 7 Biohazard,19.99,Very Positive,AAA_Action,5584,113388,118972,"[Single-player, Steam Achievements, Full con...",95.306459,4.693541,418370,26,207.896,0.953065,107804,AAA_Action

In [79]:
genres_metrics_df = merged_games_2.explode('genres')

genre_metrics = genres_metrics_df.groupby('genres').agg({
    'Profit': 'mean',
    'total_steam_purchases': 'mean',
    'app_id': 'count',
    'positive_ratio': 'mean'
}).reset_index()

genre_metrics = genre_metrics.rename(columns={
    'app_id': 'game_count',
    'Profit': 'avg_profit',
    'total_steam_purchases': 'avg_purchases',
    'positive_ratio': 'avg_positive_ratio'
})

# Calculate medians for quadrant lines
median_genre_count = genre_metrics['game_count'].median()
median_genre_profit = genre_metrics['avg_profit'].median()

fig18 = px.scatter(
    genre_metrics[genre_metrics['game_count'] >= 3],  # Filter to genres with at least 3 games
    x='game_count',
    y='avg_profit',
    color='avg_positive_ratio',
    size='avg_purchases',
    hover_name='genres',
    text='genres',
    color_continuous_scale='RdYlGn',
    title='Genre Competition vs. Profitability Quadrant Analysis',
    labels={
        'game_count': 'Number of Games (Competition)',
        'avg_profit': 'Average Profit ($)',
        'avg_positive_ratio': 'Avg. Positive Ratio'
    },
    height=700
)

# Add quadrant lines
fig18.add_shape(
    type="line", line=dict(dash="dash", width=1),
    x0=median_genre_count, y0=0, x1=median_genre_count, y1=genre_metrics['avg_profit'].max()*1.1
)
fig18.add_shape(
    type="line", line=dict(dash="dash", width=1),
    x0=0, y0=median_genre_profit, x1=genre_metrics['game_count'].max()*1.1, y1=median_genre_profit
)

# Add quadrant labels
fig18.add_annotation(x=median_genre_count/2, y=genre_metrics['avg_profit'].max()*0.9,
            text="Low Competition<br>High Profit", showarrow=False, font=dict(size=14))
fig18.add_annotation(x=genre_metrics['game_count'].max()*0.75, y=genre_metrics['avg_profit'].max()*0.9,
            text="High Competition<br>High Profit", showarrow=False, font=dict(size=14))
fig18.add_annotation(x=median_genre_count/2, y=median_genre_profit/2,
            text="Low Competition<br>Low Profit", showarrow=False, font=dict(size=14))
fig18.add_annotation(x=genre_metrics['game_count'].max()*0.75, y=median_genre_profit/2,
            text="High Competition<br>Low Profit", showarrow=False, font=dict(size=14))

fig18.update_traces(
    textposition='top center',
    textfont=dict(size=9),
    marker=dict(line=dict(width=1, color='DarkSlateGrey'))
)
fig18.update_layout(
    xaxis_title='Number of Games (Competition Level)',
    yaxis_title='Average Profit ($)'
)
fig18.show()

# **How DLCS affects profits?**

In [80]:
dlcs_data

,app_id,description,developers,genres,header_image,name,parent_app_id,price,publishers,release_date,...,supported_languages,tag,tag_id,total_english_reviews,total_negative,total_positive,total_reviews,url,website,features
0,939480,The Slime Rancher: VR Playground is a standalo...,"Monomi Park, 3lb Games","Action, Adventure, Indie, Simulation",https://shared.akamai.steamstatic.com/store_it...,Slime Rancher: VR Playground,433340,0.00,,"Nov 14, 2018",...,English,Indie_Adventure,21,0,130,241,371,https://store.steampowered.com/app/939480/,http://slimerancher.com,"Single-player, Downloadable Content, VR Suppor..."
1,1079180,Discover the secret styles of all your favorit...,Monomi Park,"Action, Adventure, Indie, Simulation",https://shared.akamai.steamstatic.com/store_it...,Slime Rancher: Secret Style Pack,433340,4.79,,"Jun 18, 2019",...,"English, French, German, Spanish - Spain, Russ...",Indie_Adventure,21,0,23,453,476,https://store.steampowered.com/app/1079180/,http://slimerancher.com,"Single-player, Downloadable Content, Steam Ach..."
2,3246790,The Great Alps is an expansion to Peaks of Yor...,Anders Grube Jensen,"Action, Adventure, Indie",https://shared.akamai.steamstatic.com/store_it...,Peaks of Yore - The Great Alps,2236070,3.89,TraipseWare,"Nov 14, 2024",...,Englishlanguages with full audio support,Indie_Platformer,1625,0,31,177,208,https://store.steampowered.com/app/3246790/,https://www.peaksofyore.net/,"Single-player, Downloadable Content, Full cont..."
3,924490,"Play A Hat in Time split-screen with a friend,...",Gears for Breakfast,"Adventure, Indie",https://shared.akamai.steamstatic.com/store_it...,A Hat in Time - Co-op,253230,0.00,Gears for Breakfast,"Sep 17, 2018",...,"English, Germanlanguages with full audio support",Indie_Platformer,1625,0,0,3,3,https://store.steampowered.com/app/924490/,http://hatintime.com/,"Single-player, Shared/Split Screen Co-op, Down..."
4,969710,You know how you have that one annoying friend...,Team Meat,Indie,https://shared.akamai.steamstatic.com/store_it...,Super Meat Boy Race Mode,40800,4.99,Team Meat,"Oct 24, 2018",...,"English, Russian",Indie_Platformer,1625,0,62,36,98,https://store.steampowered.com/app/969710/,http://www.supermeatboy.com,"Single-player, Downloadable Content, Full cont..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
653,2246730,Transform your ball with supernatural energy a...,Team17,"Casual, Indie, Sports",https://shared.akamai.steamstatic.com/store_it...,Golf With Your Friends - Horrifying Headgear Pack,431240,1.35,Team17,"May 18, 2023",...,"English, French, Italian, German, Spanish - Sp...",Rescrape,0,0,2,9,11,https://store.steampowered.com/app/2246730/,https://www.team17.com/,"Single-player, Multi-player, PvP, Online PvP, ..."
654,1277570,Turn the fairway into a runway and customise y...,Blacklight Interactive,"Casual, Indie, Sports",https://shared.akamai.steamstatic.com/store_it...,Golf With Your Friends - Caddy Pack,431240,1.35,Team17 Digital,"May 26, 2020",...,"English, French, Italian, German, Spanish - Sp...",Rescrape,0,0,19,101,120,https://store.steampowered.com/app/1277570/,https://www.team17.com/,"Single-player, Multi-player, PvP, Online PvP, ..."
655,3041150,Honour the storied past of the Gingy's homelan...,Team17,"Casual, Indie, Sports",https://shared.akamai.steamstatic.com/store_it...,Golf With Your Friends - Legends of Olympus Pack,431240,1.35,Team17,"Sep 5, 2024",...,"English, French, Italian, German, Spanish - Sp...",Rescrape,0,0,0,3,3,https://store.steampowered.com/app/3041150/,https://www.gwyf.golf/,"Single-player, Multi-player, PvP, Online PvP, ..."
656,1901922,Master the colourful hazards of the new Bouncy...,"Blacklight Interactive, Team17","Casual, Indie, Sports",https://shared.akamai.steamstatic.com/store_it...,Golf With Your Friends - Bouncy Castle Course,431240,2.24,Team17,"Jun 21, 2022",...,"English, French, Italian, German, Spanish - Sp...",Rescrape,0,0,91,106,197,https://store.steampowered.com/app/1901922/,https://www.team17.com/games/golf-with-your-fr...,"Single-player, Multi-player, PvP, Online PvP, ..."
657,2366470,An unusual meteor strike has seeped corruption...,Team17,"Casual, Indie, Sports",https://shared.akamai.steamstatic.com/store_it...,Golf With Your Friends - Corrupted Forest Course,431240,1.24,Team17,"May 18, 2023",...,"English, French, Italian, German, Spanish - Sp...",Rescrape,0,0,446,102,548,https://store.steampowered.com/app/2366470/,https://www.team17.com/,"Single-player, Multi-player, PvP, Online PvP, ..."

In [81]:
dlcs3=dlcs_data.groupby('parent_app_id').agg(
    {
        'app_id':'count',
        'price':'sum'
    }

).reset_index()
dlcs3

    parent_app_id  app_id  price
0           40800       1   4.99
1           41070       1   9.99
2          210770       5  28.95
3          219740       1   3.49
4          233450      11  56.91
..            ...     ...    ...
91        2716400       3  17.97
92        2943280       1   0.00
93        3202030       1   3.99
94        3816930       1   4.99
95        4139720       1   2.99

[96 rows x 3 columns]

In [82]:
dlcs3.rename(columns={'app_id':'dlsc_count','price':'Total Price of dlsc'},inplace=True)
dlcs3

    parent_app_id  dlsc_count  Total Price of dlsc
0           40800           1                 4.99
1           41070           1                 9.99
2          210770           5                28.95
3          219740           1                 3.49
4          233450          11                56.91
..            ...         ...                  ...
91        2716400           3                17.97
92        2943280           1                 0.00
93        3202030           1                 3.99
94        3816930           1                 4.99
95        4139720           1                 2.99

[96 rows x 3 columns]

In [83]:
game_data_cp=games_data.copy()

In [84]:
game_data_cp=game_data_cp.merge(dlcs3,
                                left_on='app_id',
                                right_on='parent_app_id',
                                how='left'  )

In [85]:
game_data_cp

,app_id,dlc_app_ids,genres,name,price,release_date,review_summary,supported_languages,tag,tag_id,total_negative,total_positive,total_reviews,features,positive_pct,negative_pct,year,parent_app_id,dlsc_count,Total Price of dlsc
0,3669570,No DLC,"[casual, indie, simulation, strategy, early ac...",Alchemy Factory,16.19,2025-12-11,Very Positive,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"[Single-player, Multi-player, Co-op, Online...",90.194306,9.805694,2025.0,NaN,NaN,NaN
1,1645820,No DLC,"[action, adventure, indie, rpg, early access]",SurrounDead,11.99,2022-06-24,Very Positive,Englishlanguages with full audio support,Indie_Action,19,1930,22234,24164,"[Single-player, Steam Achievements, Steam Tr...",92.012912,7.987088,2022.0,NaN,NaN,NaN
2,1062520,2468700,"[adventure, casual, indie, rpg, simulation]",Dinkum,15.99,2025-04-22,Very Positive,"English, French, Italian, German, Russian, Spa...",Indie_RPG,122,2297,26266,28563,"[Single-player, Multi-player, Co-op, Online...",91.958128,8.041872,2025.0,NaN,NaN,NaN
3,683320,986250,"[adventure, indie]",GRIS,14.99,2018-12-13,Very Positive,"English, French, German, Spanish - Spain, Japa...",Indie_Platformer,1625,3674,90384,94058,"[Single-player, Steam Achievements, Full con...",96.093900,3.906100,2018.0,NaN,NaN,NaN
4,1295920,2080860,"[adventure, indie, simulation]",The Mortuary Assistant,24.99,2022-08-02,Very Positive,"English, French, Portuguese - Brazil, Italian,...",Indie_Horror,1667,690,7801,8491,"[Single-player, Steam Achievements, Full con...",91.873749,8.126251,2022.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,3059520,"3493820, 3335220","[racing, simulation, sports]",F1® 25,23.99,2025-05-30,Very Positive,"English, French, Italian, German, Spanish - Sp...",AAA_Simulation,599,3050,20889,23939,"[Single-player, Multi-player, PvP, Online P...",87.259284,12.740716,2025.0,NaN,NaN,NaN
656,1435790,"3972570, 2644890, 2419810, 2175260, 1942100, 3...","[adventure, casual, indie, simulation]",Escape Simulator,19.99,2021-10-19,Overwhelmingly Positive,"English, Japanese, Korean, Simplified Chinese,...",Indie_Adventure,21,1149,17817,18966,"[Single-player, Multi-player, PvP, Online P...",93.941791,6.058209,2021.0,NaN,NaN,NaN
657,313120,1492970,"[adventure, indie]",Stranded Deep,19.99,2022-08-10,Mostly Positive,"English, French, Italian, German, Spanish - Sp...",Indie_Adventure,21,12085,35090,47175,"[Single-player, Multi-player, Co-op, Online...",74.382618,25.617382,2022.0,NaN,NaN,NaN
658,285900,1003800,"[action, adventure, casual, indie, simulation]",Gang Beasts,7.99,2017-12-12,Very Positive,"English, French, Italian, German, Spanish - Sp...",Indie_Action,19,9388,54926,64314,"[Multi-player, PvP, Online PvP, Shared/Spli...",85.402867,14.597133,2017.0,NaN,NaN,NaN
659,418370,"564190, 530611, 540340, 529930, 530610, 583810","[action, adventure]",Resident Evil 7 Biohazard,19.99,2017-01-23,Very Positive,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"[Single-player, Steam Achievements, Full con...",95.306459,4.693541,2017.0,NaN,NaN,NaN

In [86]:
games_data

,app_id,dlc_app_ids,genres,name,price,release_date,review_summary,supported_languages,tag,tag_id,total_negative,total_positive,total_reviews,features,positive_pct,negative_pct,year
0,3669570,No DLC,"[casual, indie, simulation, strategy, early ac...",Alchemy Factory,16.19,2025-12-11,Very Positive,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"[Single-player, Multi-player, Co-op, Online...",90.194306,9.805694,2025.0
1,1645820,No DLC,"[action, adventure, indie, rpg, early access]",SurrounDead,11.99,2022-06-24,Very Positive,Englishlanguages with full audio support,Indie_Action,19,1930,22234,24164,"[Single-player, Steam Achievements, Steam Tr...",92.012912,7.987088,2022.0
2,1062520,2468700,"[adventure, casual, indie, rpg, simulation]",Dinkum,15.99,2025-04-22,Very Positive,"English, French, Italian, German, Russian, Spa...",Indie_RPG,122,2297,26266,28563,"[Single-player, Multi-player, Co-op, Online...",91.958128,8.041872,2025.0
3,683320,986250,"[adventure, indie]",GRIS,14.99,2018-12-13,Very Positive,"English, French, German, Spanish - Spain, Japa...",Indie_Platformer,1625,3674,90384,94058,"[Single-player, Steam Achievements, Full con...",96.093900,3.906100,2018.0
4,1295920,2080860,"[adventure, indie, simulation]",The Mortuary Assistant,24.99,2022-08-02,Very Positive,"English, French, Portuguese - Brazil, Italian,...",Indie_Horror,1667,690,7801,8491,"[Single-player, Steam Achievements, Full con...",91.873749,8.126251,2022.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,3059520,"3493820, 3335220","[racing, simulation, sports]",F1® 25,23.99,2025-05-30,Very Positive,"English, French, Italian, German, Spanish - Sp...",AAA_Simulation,599,3050,20889,23939,"[Single-player, Multi-player, PvP, Online P...",87.259284,12.740716,2025.0
656,1435790,"3972570, 2644890, 2419810, 2175260, 1942100, 3...","[adventure, casual, indie, simulation]",Escape Simulator,19.99,2021-10-19,Overwhelmingly Positive,"English, Japanese, Korean, Simplified Chinese,...",Indie_Adventure,21,1149,17817,18966,"[Single-player, Multi-player, PvP, Online P...",93.941791,6.058209,2021.0
657,313120,1492970,"[adventure, indie]",Stranded Deep,19.99,2022-08-10,Mostly Positive,"English, French, Italian, German, Spanish - Sp...",Indie_Adventure,21,12085,35090,47175,"[Single-player, Multi-player, Co-op, Online...",74.382618,25.617382,2022.0
658,285900,1003800,"[action, adventure, casual, indie, simulation]",Gang Beasts,7.99,2017-12-12,Very Positive,"English, French, Italian, German, Spanish - Sp...",Indie_Action,19,9388,54926,64314,"[Multi-player, PvP, Online PvP, Shared/Spli...",85.402867,14.597133,2017.0
659,418370,"564190, 530611, 540340, 529930, 530610, 583810","[action, adventure]",Resident Evil 7 Biohazard,19.99,2017-01-23,Very Positive,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"[Single-player, Steam Achievements, Full con...",95.306459,4.693541,2017.0

In [87]:
game_data_cp.isna().sum()

app_id                   0
dlc_app_ids              0
genres                   0
name                     0
price                    0
release_date             1
review_summary           0
supported_languages      0
tag                      0
tag_id                   0
total_negative           0
total_positive           0
total_reviews            0
features                 0
positive_pct             1
negative_pct             1
year                     1
parent_app_id          564
dlsc_count             564
Total Price of dlsc    564
dtype: int64

In [88]:
fig18=px.scatter(
    game_data_cp,
    x='dlsc_count',
    y='total_positive',
    title='Number of DLCs vs. Total Positive Reviews',
    labels={'dlsc_count': 'Number of DLCs', 'total_positive': 'Total Positive Reviews'},
    hover_name='name',
    height=800
)

# Update axes to use logarithmic scale to decrease visual spread
fig18.update_xaxes(type='log')
fig18.update_yaxes(type='log')

fig18.show()

# So increase DLCS will increase postive reviews of app

# **Total_playtime_hours**

In [89]:
merged_data

,app_id_review,parent_app_id,recommendation,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,written_during_early_access,app_id_game,...,supported_languages,tag,tag_id,total_negative,total_positive,total_reviews,features,positive_pct,negative_pct,year
0,3669570,3669570,1,1,10.7,10.7,0,0,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
1,3669570,3669570,1,1,70.2,70.2,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
2,3669570,3669570,1,1,1376.0,1364.8,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
3,3669570,3669570,0,0,2.3,2.3,2,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
4,3669570,3669570,1,1,39.0,5.0,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19486,418370,418370,1,1,11.8,11.8,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19487,418370,418370,1,1,33.6,29.6,1,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19488,418370,418370,1,1,14.6,13.1,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19489,418370,418370,1,1,9.3,5.0,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19490,418370,418370,1,1,15.4,15.0,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0

In [90]:
hours_data=merged_data[['tag','total_playtime_hours']]
hours_data

                  tag  total_playtime_hours
0      Indie_Strategy                  10.7
1      Indie_Strategy                  70.2
2      Indie_Strategy                1376.0
3      Indie_Strategy                   2.3
4      Indie_Strategy                  39.0
...               ...                   ...
19486      AAA_Action                  11.8
19487      AAA_Action                  33.6
19488      AAA_Action                  14.6
19489      AAA_Action                   9.3
19490      AAA_Action                  15.4

[19491 rows x 2 columns]

In [91]:
hours_data.groupby('tag').agg({'total_playtime_hours':'sum'}).reset_index()

                 tag  total_playtime_hours
0         AAA_Action              709513.1
1      AAA_Adventure               40201.8
2   AAA_Early Access                1492.6
3            AAA_RPG              121676.3
4         AAA_Racing                5538.5
5     AAA_Simulation              111370.8
6       Indie_Action              232733.2
7    Indie_Adventure               67196.7
8       Indie_Casual              118393.9
9          Indie_FPS              213482.9
10      Indie_Horror               47507.5
11  Indie_Open World               53085.3
12  Indie_Platformer               66719.9
13      Indie_Puzzle              183756.4
14         Indie_RPG              172747.5
15  Indie_Simulation               58923.9
16    Indie_Strategy               89774.8
17    Indie_Survival              180248.4

In [92]:
aggregated_playtime = hours_data.groupby('tag').agg({'total_playtime_hours':'sum'}).reset_index()

aggregated_playtime = aggregated_playtime.sort_values('total_playtime_hours', ascending=False)

fig = px.bar(
    aggregated_playtime,
    x='total_playtime_hours',
    y='tag',
    orientation='h',
    title='Total Playtime Hours by Game Tag',
    labels={'tag': 'Game Tag', 'total_playtime_hours': 'Total Playtime Hours (Sum)'},
    color='total_playtime_hours',
    color_continuous_scale='Plasma',
    height=600
)

fig.update_layout(
    xaxis_title='Total Playtime Hours',
    yaxis_title='Game Tag',
    yaxis={'categoryorder': 'total ascending'},
    font=dict(size=12)
)

fig.show()

# **ML model (Predict tag)**

In [93]:
merged_data

,app_id_review,parent_app_id,recommendation,review_score,total_playtime_hours,playtime_at_review_hours,votes_up,steam_purchase,written_during_early_access,app_id_game,...,supported_languages,tag,tag_id,total_negative,total_positive,total_reviews,features,positive_pct,negative_pct,year
0,3669570,3669570,1,1,10.7,10.7,0,0,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
1,3669570,3669570,1,1,70.2,70.2,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
2,3669570,3669570,1,1,1376.0,1364.8,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
3,3669570,3669570,0,0,2.3,2.3,2,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
4,3669570,3669570,1,1,39.0,5.0,0,1,1,3669570,...,"English, Simplified Chinese, Japanese, French,...",Indie_Strategy,9,217,1996,2213,"Single-player, Multi-player, Co-op, Online Co-...",90.194306,9.805694,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19486,418370,418370,1,1,11.8,11.8,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19487,418370,418370,1,1,33.6,29.6,1,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19488,418370,418370,1,1,14.6,13.1,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19489,418370,418370,1,1,9.3,5.0,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0
19490,418370,418370,1,1,15.4,15.0,0,1,0,418370,...,"English, French, Italian, German, Spanish - Sp...",AAA_Action,19,5584,113388,118972,"Single-player, Steam Achievements, Full contro...",95.306459,4.693541,2017.0

In [94]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [95]:
X=merged_data[['recommendation','review_score','total_playtime_hours','total_positive','total_negative']]
y=merged_data['tag']

In [96]:
KN=KNeighborsClassifier(n_neighbors=11, p=2, metric='euclidean')
NB=GaussianNB()
RF=RandomForestClassifier()
DT = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)

In [97]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3, random_state=42)

In [98]:
x_train2,x_test2,y_train2,y_test2=train_test_split(X,y,test_size=0.3, random_state=42)

In [99]:
x_train3,x_test3,y_train3,y_test3=train_test_split(X,y,test_size=0.3, random_state=42)

In [100]:
x_train4,x_test4,y_train4,y_test4=train_test_split(X,y,test_size=0.3, random_state=42)

In [101]:
KN.fit (x_train,y_train)
NB.fit   (x_train2,y_train2)
RF.fit  (x_train3,y_train3)
DT.fit  (x_train4,y_train4)

DecisionTreeClassifier(criterion='entropy', random_state=0)

KNN

In [102]:
y1=KN.predict(x_test)
score=round(accuracy_score(y1,y_test), 4)
print(score)

0.9836

GaussianNB

In [103]:
y2=NB.predict(x_test2)
score2=round(accuracy_score(y2,y_test2),4)
print(score2)

0.1708

RandomForestClassifier

In [104]:
y3=RF.predict(x_test3)
score3=round(accuracy_score(y3,y_test3),4)
print(score3)

0.959

DecisionTreeClassifier

In [105]:
y4=DT.predict(x_test4)
score4=round(accuracy_score(y4,y_test4),4)
print(score4)

0.9973

In [106]:
model_names = ['KNN', 'GaussianNB', 'RandomForestClassifier', 'DecisionTreeClassifier']
accuracies = [score, score2, score3, score4]

accuracy_df = pd.DataFrame({
    'Model': model_names,
    'Accuracy': accuracies
})

display(accuracy_df)

                    Model  Accuracy
0                     KNN    0.9836
1              GaussianNB    0.1708
2  RandomForestClassifier    0.9590
3  DecisionTreeClassifier    0.9973

In [107]:
fig = px.bar(
    accuracy_df.sort_values(by='Accuracy', ascending=True), # Sort ascending for horizontal bar chart display
    x='Accuracy',
    y='Model',
    orientation='h',
    title='Model Accuracy Comparison (Horizontal Bar Chart)',
    labels={'Model': 'Machine Learning Model', 'Accuracy': 'Accuracy Score'},
    color='Accuracy',
    color_continuous_scale='twilight',
    height=600
)



fig.update_layout(
    xaxis_title='Accuracy Score',
    yaxis_title='Machine Learning Model',
    xaxis_range=[0, 1.05],
    font=dict(size=12)
)

fig.update_traces(texttemplate='%{x:.4f}', textposition='outside')

fig.show()

### AAA Game Tag Performance Analysis

In [108]:
aaa_df = tag_df[tag_df['tag'].str.contains('AAA_')].sort_values('Average Profit (M)', ascending=False)

fig_aaa = make_subplots(
    rows=2, cols=2,
    specs=[[{"type": "bar"}, {"type": "scatter"}],
           [{"type": "bar", "colspan": 2}, None]],
    subplot_titles=("AAA - Average Profit by Tag (Millions $)",
                   "AAA - Profit vs. Review Sentiment",
                   "AAA - Average Profit per Game by Tag (Millions $)"),
    vertical_spacing=0.12,
    horizontal_spacing=0.08
)

# 1. Bar chart for Average Profit by Tag (AAA)
fig_aaa.add_trace(
    go.Bar(
        x=aaa_df['tag'],
        y=aaa_df['Average Profit (M)'],
        marker_color=aaa_df['positive%'],
        marker_colorbar=dict(title="Positive %"),
        marker_colorscale='RdYlGn',
        text=aaa_df['Average Profit (M)'].apply(lambda x: f"${x:.1f}M"),
        textposition='auto',
        name='Total Profit'
    ),
    row=1, col=1
)

# 2. Scatter plot for Profit vs Sentiment with size as Total Reviews (AAA)
fig_aaa.add_trace(
    go.Scatter(
        x=aaa_df['positive%'],
        y=aaa_df['Average Profit (M)'],
        mode='markers',
        marker=dict(
            size=aaa_df['Total Reviews'].apply(lambda x: min(max(x/10000, 10), 50)),
            color=aaa_df['avg_price'],
            colorscale='Viridis',
            colorbar=dict(title="Avg Price ($)"),
            showscale=True
        ),
        text=aaa_df['tag'],
        hovertemplate='<b>%{text}</b><br>Positive: %{x:.1f}%<br>Profit: $%{y:.1f}M<br>Reviews: %{marker.size}<br>Avg Price: $%{marker.color:.2f}<extra></extra>',
        name='Tag Performance'
    ),
    row=1, col=2
)

# 3. Bar chart for Average Profit per Game (AAA)
fig_aaa.add_trace(
    go.Bar(
        x=aaa_df['tag'],
        y=aaa_df['Average Profit per game (M)'],
        marker_color=aaa_df['Game Count'],
        marker_colorscale='Blues',
        marker_colorbar=dict(title="Game Count"),
        text=aaa_df['Average Profit per game (M)'].apply(lambda x: f"${x:.2f}M"),
        textposition='auto',
        name='Profit per Game'
    ),
    row=2, col=1
)

# Update layout
fig_aaa.update_layout(
    title_text="AAA Game Tag Performance Analysis",
    height=900,
    width=1200,
    template="plotly_white",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    font=dict(family="Arial", size=12)
)

# Update axes
fig_aaa.update_xaxes(tickangle=45, row=1, col=1)
fig_aaa.update_xaxes(tickangle=45, row=2, col=1)
fig_aaa.update_xaxes(title_text="Positive Reviews (%)", row=1, col=2)
fig_aaa.update_yaxes(title_text="Average Profit (Millions $)", row=1, col=1)
fig_aaa.update_yaxes(title_text="Average Profit (Millions $)", row=1, col=2)
fig_aaa.update_yaxes(title_text="Average Profit per Game (Millions $)", row=2, col=1)

fig_aaa.show()

### Indie Game Tag Performance Analysis

In [109]:
indie_df = tag_df[tag_df['tag'].str.contains('Indie_')].sort_values('Average Profit (M)', ascending=False)

fig_indie = make_subplots(
    rows=2, cols=2,
    specs=[[{"type": "bar"}, {"type": "scatter"}],
           [{"type": "bar", "colspan": 2}, None]],
    subplot_titles=("Indie - Average Profit by Tag (Millions $)",
                   "Indie - Profit vs. Review Sentiment",
                   "Indie - Average Profit per Game by Tag (Millions $)"),
    vertical_spacing=0.12,
    horizontal_spacing=0.08
)

# 1. Bar chart for Average Profit by Tag (Indie)
fig_indie.add_trace(
    go.Bar(
        x=indie_df['tag'],
        y=indie_df['Average Profit (M)'],
        marker_color=indie_df['positive%'],
        marker_colorbar=dict(title="Positive %"),
        marker_colorscale='RdYlGn',
        text=indie_df['Average Profit (M)'].apply(lambda x: f"${x:.1f}M"),
        textposition='auto',
        name='Total Profit'
    ),
    row=1, col=1
)

# 2. Scatter plot for Profit vs Sentiment with size as Total Reviews (Indie)
fig_indie.add_trace(
    go.Scatter(
        x=indie_df['positive%'],
        y=indie_df['Average Profit (M)'],
        mode='markers',
        marker=dict(
            size=indie_df['Total Reviews'].apply(lambda x: min(max(x/10000, 10), 50)),
            color=indie_df['avg_price'],
            colorscale='Viridis',
            colorbar=dict(title="Avg Price ($)"),
            showscale=True
        ),
        text=indie_df['tag'],
        hovertemplate='<b>%{text}</b><br>Positive: %{x:.1f}%<br>Profit: $%{y:.1f}M<br>Reviews: %{marker.size}<br>Avg Price: $%{marker.color:.2f}<extra></extra>',
        name='Tag Performance'
    ),
    row=1, col=2
)

# 3. Bar chart for Average Profit per Game (Indie)
fig_indie.add_trace(
    go.Bar(
        x=indie_df['tag'],
        y=indie_df['Average Profit per game (M)'],
        marker_color=indie_df['Game Count'],
        marker_colorscale='Blues',
        marker_colorbar=dict(title="Game Count"),
        text=indie_df['Average Profit per game (M)'].apply(lambda x: f"${x:.2f}M"),
        textposition='auto',
        name='Profit per Game'
    ),
    row=2, col=1
)

# Update layout
fig_indie.update_layout(
    title_text="Indie Game Tag Performance Analysis",
    height=900,
    width=1200,
    template="plotly_white",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    font=dict(family="Arial", size=12)
)

# Update axes
fig_indie.update_xaxes(tickangle=45, row=1, col=1)
fig_indie.update_xaxes(tickangle=45, row=2, col=1)
fig_indie.update_xaxes(title_text="Positive Reviews (%)", row=1, col=2)
fig_indie.update_yaxes(title_text="Average Profit (Millions $)", row=1, col=1)
fig_indie.update_yaxes(title_text="Average Profit (Millions $)", row=1, col=2)
fig_indie.update_yaxes(title_text="Average Profit per Game (Millions $)", row=2, col=1)

fig_indie.show()